name: "Build and Deploy to Cloud Run"

on:
  push:
    branches:
      - "master"

env:
  PROJECT_ID: "${{ secrets.PROJECT_ID }}"
  GCR_REGION: "${{ secrets.GCR_REGION }}"
  GCR_SERVICE: "${{ secrets.GCR_SERVICE }}"
  GAR_REGION: "${{ secrets.GAR_REGION }}"
  GAR_IMAGE_NAME: "${{ secrets.GAR_IMAGE_NAME }}"
  GAR_REPO_NAME: "${{ secrets.GAR_REPO_NAME }}"

jobs:
  deploy:
    runs-on: "ubuntu-latest"

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Authenticate to GCP"
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDS }}"

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Docker Auth To GAR"
        run: |
          gcloud auth configure-docker "${{env.GAR_REGION}}-docker.pkg.dev"

      - name: "Build and Push To GAR"
        run: |-
          DOCKER_TAG="${{ env.GAR_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO_NAME }}/${{ env.GAR_IMAGE_NAME }}:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.GCR_SERVICE }} \
            --image ${{ env.GAR_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO_NAME }}/${{ env.GAR_IMAGE_NAME }}:${{ github.sha }} \
            --platform managed \
            --region ${{ env.GCR_REGION }} \
            --port ${{ secrets.NOTI_SERVER_PORT }} \
            --allow-unauthenticated \
            --set-env-vars NOTI_SERVER_PORT=${{ secrets.NOTI_SERVER_PORT }} \
            --set-env-vars SMS_AUTH_TOKEN=${{ secrets.SMS_AUTH_TOKEN }} \
            --set-env-vars SMS_API_URL=${{ secrets.SMS_API_URL }} \
            --set-env-vars SENDER_ID=${{ secrets.SENDER_ID }} \
            --set-env-vars MAILGUN_KEY=${{ secrets.MAILGUN_KEY }} \
            --set-env-vars MAILGUN_USERNAME=${{ secrets.MAILGUN_USERNAME }} \
            --set-env-vars MAILGUN_DOMAIN=${{ secrets.MAILGUN_DOMAIN }} \
            --set-env-vars MONGO_URL=${{ secrets.MONGO_URL }}

      - name: "Show Cloud Run URL"
        run: |
          echo "Cloud Run URL:"
          gcloud run services describe ${{ env.GCR_SERVICE }} --platform managed --region ${{ env.GCR_REGION }} --format='value(status.url)'
